import pandas as pd

tempnagpurl=pd.read_excel(io='Data/Temperature_pandas_labels.xlsx',sheet_name='Nagpur')
temppunel=pd.read_excel(io='Data/Temperature_pandas_labels.xlsx',sheet_name='Pune')
tempnashikl=pd.read_excel(io='Data/Temperature_pandas_labels.xlsx',sheet_name='Nashik')
tempaurangabadl=pd.read_excel(io='Data/Temperature_pandas_labels.xlsx',sheet_name='Aurangabad')
tempamravatil=pd.read_excel(io='Data/Temperature_pandas_labels.xlsx',sheet_name='Amravati')
tempsolapurl=pd.read_excel(io='Data/Temperature_pandas_labels.xlsx',sheet_name='Solapur')
tempyavatmall=pd.read_excel(io='Data/Temperature_pandas_labels.xlsx',sheet_name='Yavatmal')
templaturl=pd.read_excel(io='Data/Temperature_pandas_labels.xlsx',sheet_name='Latur')

pressnagpurl=pd.read_excel(io='Data/Pressure_pandas_labels.xlsx',sheet_name='Nagpur')
presspunel=pd.read_excel(io='Data/Pressure_pandas_labels.xlsx',sheet_name='Pune')
pressnashikl=pd.read_excel(io='Data/Pressure_pandas_labels.xlsx',sheet_name='Nashik')
pressaurangabadl=pd.read_excel(io='Data/Pressure_pandas_labels.xlsx',sheet_name='Aurangabad')
pressamravatil=pd.read_excel(io='Data/Pressure_pandas_labels.xlsx',sheet_name='Amravati')
presssolapurl=pd.read_excel(io='Data/Pressure_pandas_labels.xlsx',sheet_name='Solapur')
pressyavatmall=pd.read_excel(io='Data/Pressure_pandas_labels.xlsx',sheet_name='Yavatmal')
presslaturl=pd.read_excel(io='Data/Pressure_pandas_labels.xlsx',sheet_name='Latur')

rfnagpurl=pd.read_excel(io='Data/Rainfall_pandas_labels.xlsx',sheet_name='Nagpur')
rfpunel=pd.read_excel(io='Data/Rainfall_pandas_labels.xlsx',sheet_name='Pune')
rfnashikl=pd.read_excel(io='Data/Rainfall_pandas_labels.xlsx',sheet_name='Nashik')
rfaurangabadl=pd.read_excel(io='Data/Rainfall_pandas_labels.xlsx',sheet_name='Aurangabad')
rfamravatil=pd.read_excel(io='Data/Rainfall_pandas_labels.xlsx',sheet_name='Amravati')
rfsolapurl=pd.read_excel(io='Data/Rainfall_pandas_labels.xlsx',sheet_name='Solapur')
rfyavatmall=pd.read_excel(io='Data/Rainfall_pandas_labels.xlsx',sheet_name='Yavatmal')
rflaturl=pd.read_excel(io='Data/Rainfall_pandas_labels.xlsx',sheet_name='Latur')

nagpurdroughtyn=pd.read_excel(io='Data/Drought10_pandas_labels.xlsx',sheet_name='Nagpur')
punedroughtyn=pd.read_excel(io='Data/Drought10_pandas_labels.xlsx',sheet_name='Pune')
nashikdroughtyn=pd.read_excel(io='Data/Drought10_pandas_labels.xlsx',sheet_name='Nashik')
aurangabaddroughtyn=pd.read_excel(io='Data/Drought10_pandas_labels.xlsx',sheet_name='Aurangabad')
amravatidroughtyn=pd.read_excel(io='Data/Drought10_pandas_labels.xlsx',sheet_name='Amravati')
solapurdroughtyn=pd.read_excel(io='Data/Drought10_pandas_labels.xlsx',sheet_name='Solapur')
yavatmaldroughtyn=pd.read_excel(io='Data/Drought10_pandas_labels.xlsx',sheet_name='Yavatmal')
laturdroughtyn=pd.read_excel(io='Data/Drought10_pandas_labels.xlsx',sheet_name='Latur')